import mysql from 'mysql2/promise';
import * as dotenv from 'dotenv';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
const __dirname = dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: join(__dirname, '../.env') });
const conn = await mysql.createConnection(process.env.DATABASE_URL + '?charset=utf8mb4');
const [u] = await conn.execute("SELECT id, openId, name, role, deletedAt FROM users WHERE id=697");
console.log('697 계정:', u[0]);
const [q] = await conn.execute("SELECT id, title, customerId FROM quotes WHERE customerId=697");
console.log(`\n697이 의뢰한 견적: ${q.length}건`);
q.forEach(x => console.log(`  id=${x.id} "${x.title}"`));
await conn.end();
